services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: clash-royale-backend
    ports:
      - "5000:5000"
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: clash-royale-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend